/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTreeRouteImport } from './routes/api/tree'
import { Route as ApiHelloRouteImport } from './routes/api/hello'
import { Route as ApiTreesIndexRouteImport } from './routes/api/trees/index'
import { Route as ApiAuthSyncRouteImport } from './routes/api/auth/sync'
import { Route as ApiAuthProfileRouteImport } from './routes/api/auth/profile'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTreeRoute = ApiTreeRouteImport.update({
  id: '/api/tree',
  path: '/api/tree',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHelloRoute = ApiHelloRouteImport.update({
  id: '/api/hello',
  path: '/api/hello',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTreesIndexRoute = ApiTreesIndexRouteImport.update({
  id: '/api/trees/',
  path: '/api/trees/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSyncRoute = ApiAuthSyncRouteImport.update({
  id: '/api/auth/sync',
  path: '/api/auth/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthProfileRoute = ApiAuthProfileRouteImport.update({
  id: '/api/auth/profile',
  path: '/api/auth/profile',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/api/hello': typeof ApiHelloRoute
  '/api/tree': typeof ApiTreeRoute
  '/api/auth/profile': typeof ApiAuthProfileRoute
  '/api/auth/sync': typeof ApiAuthSyncRoute
  '/api/trees/': typeof ApiTreesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/api/hello': typeof ApiHelloRoute
  '/api/tree': typeof ApiTreeRoute
  '/api/auth/profile': typeof ApiAuthProfileRoute
  '/api/auth/sync': typeof ApiAuthSyncRoute
  '/api/trees': typeof ApiTreesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/api/hello': typeof ApiHelloRoute
  '/api/tree': typeof ApiTreeRoute
  '/api/auth/profile': typeof ApiAuthProfileRoute
  '/api/auth/sync': typeof ApiAuthSyncRoute
  '/api/trees/': typeof ApiTreesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/builder'
    | '/dashboard'
    | '/login'
    | '/settings'
    | '/api/hello'
    | '/api/tree'
    | '/api/auth/profile'
    | '/api/auth/sync'
    | '/api/trees/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/builder'
    | '/dashboard'
    | '/login'
    | '/settings'
    | '/api/hello'
    | '/api/tree'
    | '/api/auth/profile'
    | '/api/auth/sync'
    | '/api/trees'
  id:
    | '__root__'
    | '/'
    | '/builder'
    | '/dashboard'
    | '/login'
    | '/settings'
    | '/api/hello'
    | '/api/tree'
    | '/api/auth/profile'
    | '/api/auth/sync'
    | '/api/trees/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuilderRoute: typeof BuilderRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  ApiHelloRoute: typeof ApiHelloRoute
  ApiTreeRoute: typeof ApiTreeRoute
  ApiAuthProfileRoute: typeof ApiAuthProfileRoute
  ApiAuthSyncRoute: typeof ApiAuthSyncRoute
  ApiTreesIndexRoute: typeof ApiTreesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tree': {
      id: '/api/tree'
      path: '/api/tree'
      fullPath: '/api/tree'
      preLoaderRoute: typeof ApiTreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hello': {
      id: '/api/hello'
      path: '/api/hello'
      fullPath: '/api/hello'
      preLoaderRoute: typeof ApiHelloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trees/': {
      id: '/api/trees/'
      path: '/api/trees'
      fullPath: '/api/trees/'
      preLoaderRoute: typeof ApiTreesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/sync': {
      id: '/api/auth/sync'
      path: '/api/auth/sync'
      fullPath: '/api/auth/sync'
      preLoaderRoute: typeof ApiAuthSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/profile': {
      id: '/api/auth/profile'
      path: '/api/auth/profile'
      fullPath: '/api/auth/profile'
      preLoaderRoute: typeof ApiAuthProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuilderRoute: BuilderRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  ApiHelloRoute: ApiHelloRoute,
  ApiTreeRoute: ApiTreeRoute,
  ApiAuthProfileRoute: ApiAuthProfileRoute,
  ApiAuthSyncRoute: ApiAuthSyncRoute,
  ApiTreesIndexRoute: ApiTreesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
